# Generated by Django 3.2.6 on 2021-08-13 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8b881e3d-dc9d-40dc-b6f9-07c0472285c6'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reorder_level', models.IntegerField(default=5)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
